version: "3.9"

services:
  teste_api:
    build: .
    container_name: teste_api_container
    volumes:
      - ./:/tests
      - ./results:/results
    working_dir: /tests
    command: robot -d /results -K off .
    tty: true